#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the TS→Zy compat mirror Lua self-test.

The Lua output validates all archived function names are registered. Safe
implemented entries are called with conservative sample arguments; planned,
unsupported and generic stubs are expected to return honest false/error tags.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MIRROR = ROOT / "tools/ziyan_doc/ts_zy_mirror_map.json"
OUT = ROOT / "tmp_shots/PHASE763R8/api_selftest/compat_mirror_selftest.lua"

PURE_EXPECT = {
    "intToRgb": "rgb255",
    "rgbToInt": "intwhite",
    "urlEncode": "urlenc",
    "urlDecode": "urldec",
    "trim": "trim",
    "getRndNum": "number",
    "rnd": "number",
    "random": "number",
    "getTime": "number",
    "getServerTime": "number",
    "split": "table",
    "toTableType": "table",
    "toStringType": "string",
}


def q(s: str) -> str:
    return json.dumps(s or "", ensure_ascii=False)


def main() -> None:
    data = json.loads(MIRROR.read_text(encoding="utf-8"))
    lines = []
    for name, meta in sorted((data.get("functions") or {}).items()):
        lines.append(
            "  {n=%s,s=%s,i=%s,b=%s,e=%s},"
            % (
                q(name),
                q(meta.get("status")),
                q(meta.get("zy_impl")),
                q(meta.get("bucket")),
                q(PURE_EXPECT.get(name, "")),
            )
        )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        """-- AUTO-GENERATED by tools/ziyan_doc/generate_compat_mirror_selftest.py
-- TS→Zy 镜像入口双机测试；只测 ZiYan 自研后端/诚实 stub，不调用触动私有 API。

local VAR = _G.ZIYAN_VAR or "/usr/lib/ziyan/var"
local SCRIPTS = _G.ZIYAN_SCRIPTS or "/private/var/mobile/Media/ZiYan"
local OUT1 = VAR .. "/compat_mirror_result.txt"
local OUT2 = SCRIPTS .. "/ZYCV/compat_mirror_result.txt"
local HB = VAR .. "/.ziyan_compat_mirror_hb"
local pass_n, fail_n, skip_n = 0, 0, 0
local rows = {}

local function now() return os.date("%Y-%m-%d %H:%M:%S") end
local function log(s) rows[#rows + 1] = s; print(s) end
local function hb()
  local f = io.open(HB, "w")
  if f then f:write(string.format("ts=%s pass=%d fail=%d skip=%d\\n", now(), pass_n, fail_n, skip_n)); f:close() end
end
local function write_out()
  local body = table.concat(rows, "\\n") .. "\\n"
  for _, p in ipairs({OUT1, OUT2}) do
    local dir = p:match("(.+)/[^/]+$")
    if dir then os.execute("mkdir -p '" .. dir .. "' 2>/dev/null") end
    local f = io.open(p, "w")
    if f then f:write(body); f:close() end
  end
end
local function PASS(n, d) pass_n = pass_n + 1; log("[PASS] " .. n .. " " .. (d or "")); hb() end
local function FAIL(n, d) fail_n = fail_n + 1; log("[FAIL] " .. n .. " " .. (d or "")); hb() end
local function SKIP(n, d) skip_n = skip_n + 1; log("[SKIP] " .. n .. " " .. (d or "")); hb() end

local function getfn(name)
  local node = _G
  for part in tostring(name):gmatch("[^%.]+") do
    node = type(node) == "table" and node[part] or nil
  end
  return node
end

local function callable(v)
  if type(v) == "function" then return true end
  local mt = type(v) == "table" and getmetatable(v) or nil
  return type(mt) == "table" and type(mt.__call) == "function"
end

local function args_for(impl)
  local m = {
    ["color.getColor"] = {10, 10},
    ["color.getColorRGB"] = {10, 10},
    ["color.isColor"] = {10, 10, 0x000000, 1},
    ["color.isColors"] = {{{10, 10, 0x000000}}, 1},
    ["color.multiColor"] = {{{10, 10, 0x000000}}, 1},
    ["color.muColors"] = {{{{10, 10, 0x000000}}}, 1},
    ["color.findColor"] = {0x000000, 0, 0, 30, 30},
    ["color.findColorUntil"] = {0x000000, 1, 0, 0, 30, 30},
    ["color.findColorInRegionFuzzy"] = {0x000000, 1, 0, 0, 30, 30},
    ["color.findMultiColor"] = {0x000000, "0|0|0x000000", 1, 0, 0, 30, 30},
    ["color.findMultiColorInRegionFuzzy"] = {0x000000, "0|0|0x000000", 1, 0, 0, 30, 30},
    ["color.findMultiColorInRegionFuzzyExt"] = {0x000000, "0|0|0x000000", 1, 0, 0, 30, 30},
    ["color.findMultiColorInRegionFuzzyByTable"] = {{{0, 0, 0x000000}}, 1, 0, 0, 30, 30},
    ["color.findColorsUntil"] = {{{10, 10, 0x000000}}, 1, 1},
    ["color.intToRgb"] = {0xffffff},
    ["color.rgbToInt"] = {255, 255, 255},
    ["color.toTableType"] = {"0|0|0xffffff"},
    ["color.toStringType"] = {{{0, 0, 0xffffff}}},
    ["touch.tap"] = {20, 20},
    ["touch.touchDown"] = {1, 20, 20},
    ["touch.touchMove"] = {1, 22, 22},
    ["touch.touchUp"] = {1, 22, 22},
    ["touch.swipe"] = {20, 20, 30, 20, 80},
    ["touch.longTap"] = {20, 20, 80},
    ["screen.keepScreen"] = {false},
    ["screen.snapshot"] = {SCRIPTS .. "/ZYCV/_compat_snap.png"},
    ["screen.init"] = {1},
    ["time.mSleep"] = {1},
    ["time.sleep"] = {0},
    ["input.inputText"] = {""},
    ["input.inputStr"] = {""},
    ["input.inputKey"] = {"A"},
    ["input.keyDown"] = {"A"},
    ["input.keyUp"] = {"A"},
    ["input.copyText"] = {"compat"},
    ["input.writePasteboard"] = {"compat"},
    ["app.isAppInstalled"] = {"com.apple.Preferences"},
    ["app.appIsRunning"] = {"com.apple.Preferences"},
    ["file.getList"] = {SCRIPTS},
    ["file.readFile"] = {SCRIPTS .. "/ZYCV/_compat_no_file"},
    ["file.writeFile"] = {SCRIPTS .. "/ZYCV/_compat_tmp.txt", "ok"},
    ["file.delFile"] = {SCRIPTS .. "/ZYCV/_compat_tmp.txt"},
    ["file.isFileExist"] = {SCRIPTS},
    ["file.mkdir"] = {SCRIPTS .. "/ZYCV"},
    ["log.toast"] = {"compat", 200},
    ["log.notifyMessage"] = {"compat", 200},
    ["log.sysLog"] = {"compat"},
    ["log.nLog"] = {"compat"},
    ["log.dialog"] = {"compat"},
    ["util.getRndNum"] = {1, 3},
    ["util.md5"] = {"x"},
    ["util.base64Encode"] = {"x"},
    ["util.base64Decode"] = {"eA=="},
    ["util.jsonEncode"] = {{a = 1}},
    ["util.jsonDecode"] = {"{}"},
    ["util.urlEncode"] = {"a b"},
    ["util.urlDecode"] = {"a%20b"},
    ["util.split"] = {"a,b", ","},
    ["util.trim"] = {" x "},
    ["image.findImage"] = {SCRIPTS .. "/ZYCV/_none.png", 0, 0, 30, 30},
    ["ocr.ocrText"] = {0, 0, 30, 30},
  }
  return m[impl] or {}
end

local hazard = {
  ["app.runApp"] = true, ["app.closeApp"] = true, ["device.unlockDevice"] = true,
  ["device.setBrightness"] = true, ["device.vibrate"] = true, ["device.playAudio"] = true,
  ["device.openURL"] = true, ["script.lua_exit"] = true,
  ["color.findColorUntil"] = true, ["color.findColorsUntil"] = true,
  ["app.isAppInstalled"] = true, ["app.appIsRunning"] = true,
  ["device.getOSVer"] = true, ["device.getDeviceType"] = true,
  ["device.getScreenScale"] = true, ["device.getNetIP"] = true,
  ["device.getBatteryLevel"] = true, ["device.getBrightness"] = true,
  ["file.getList"] = true,
  ["input.inputText"] = true, ["input.inputStr"] = true, ["input.inputKey"] = true,
  ["input.keyDown"] = true, ["input.keyUp"] = true,
  ["keycode.home"] = true, ["keycode.back"] = true, ["keycode.power"] = true,
  ["file.isFileExist"] = true, ["file.readFile"] = true, ["file.writeFile"] = true, ["file.delFile"] = true, ["file.mkdir"] = true,
  ["input.readPasteboard"] = true, ["input.writePasteboard"] = true, ["input.copyText"] = true,
  ["screen.snapshot"] = true, ["screen.resetScreen"] = true,
  ["touch.tap"] = true, ["touch.touchDown"] = true, ["touch.touchMove"] = true,
  ["touch.touchUp"] = true, ["touch.swipe"] = true, ["touch.longTap"] = true,
  ["log.toast"] = true, ["log.notifyMessage"] = true, ["log.dialog"] = true,
}

local function check_expect(kind, a, b, c)
  if kind == "" then return true end
  if kind == "rgb255" then return a == 255 and b == 255 and c == 255 end
  if kind == "intwhite" then return a == 16777215 end
  if kind == "urlenc" then return a == "a%20b" end
  if kind == "urldec" then return a == "a b" end
  if kind == "trim" then return a == "x" end
  if kind == "number" then return type(a) == "number" end
  if kind == "table" then return type(a) == "table" end
  if kind == "string" then return type(a) == "string" end
  return true
end

local entries = {
"""
        + "\n".join(lines)
        + """
}

local function main()
  log("=== ZiYan compat mirror selftest " .. now() .. " ===")
  local root = _G.ZIYAN_LUA
  if type(root) ~= "string" or root == "" then
    root = (io.open("/var/jb/usr/lib/ziyan/lib/lua/ziyan_engine/init.lua", "r") and "/var/jb/usr/lib/ziyan/lib/lua") or "/usr/lib/ziyan/lib/lua"
    _G.ZIYAN_LUA = root
  end
  local ok_engine, err = pcall(dofile, root .. "/ziyan_engine/init.lua")
  if not ok_engine then FAIL("engine.load", tostring(err)); write_out(); return end
  PASS("engine.load", tostring(root))
  if not (_G.Zy and Zy.Compat and tonumber(Zy.Compat.count or 0) >= #entries) then
    FAIL("Zy.Compat.count", tostring(Zy and Zy.Compat and Zy.Compat.count))
  else
    PASS("Zy.Compat.count", tostring(Zy.Compat.count))
  end

  local by_status = {}
  for _, it in ipairs(entries) do
    by_status[it.s] = (by_status[it.s] or 0) + 1
    local fn = getfn(it.n)
    if not callable(fn) then
      FAIL(it.n, "missing status=" .. it.s .. " impl=" .. it.i)
    elseif it.s == "implemented" then
      if hazard[it.i] then
        PASS(it.n, "registered_hazard_guard impl=" .. it.i)
      else
        local ok, a, b, c = pcall(fn, table.unpack(args_for(it.i)))
        if not ok then
          FAIL(it.n, "error=" .. tostring(a):sub(1, 120) .. " impl=" .. it.i)
        elseif not check_expect(it.e, a, b, c) then
          FAIL(it.n, string.format("bad_ret expect=%s a=%s b=%s c=%s", it.e, tostring(a), tostring(b), tostring(c)))
        else
          PASS(it.n, "called impl=" .. it.i .. " a=" .. tostring(a):sub(1, 40))
        end
      end
    else
      local ok, a, b = pcall(fn)
      if not ok then
        PASS(it.n, "native_preserved_requires_args " .. tostring(a):sub(1, 80))
      elseif a ~= false then
        PASS(it.n, "native_preserved a=" .. tostring(a):sub(1, 40))
      else
        local tag = tostring(b or "")
        if it.s == "stub_unsupported" and not tag:find("unsupported", 1, true) then
          FAIL(it.n, "unsupported_bad_tag=" .. tag)
        elseif it.s == "stub_planned" and not tag:find("not_implemented:planned", 1, true) then
          FAIL(it.n, "planned_bad_tag=" .. tag)
        elseif it.s == "stub_generic" and not tag:find("not_implemented:generic", 1, true) then
          FAIL(it.n, "generic_bad_tag=" .. tag)
        else
          PASS(it.n, "honest_stub " .. tag)
        end
      end
    end
    if (pass_n + fail_n + skip_n) % 25 == 0 then hb() end
  end

  local stat = {}
  for k, v in pairs(by_status) do stat[#stat + 1] = k .. "=" .. tostring(v) end
  log("[STATS] " .. table.concat(stat, " "))
  log(string.format("=== SUMMARY pass=%d fail=%d skip=%d total=%d ===", pass_n, fail_n, skip_n, #entries))
  write_out()
end

main()
""",
        encoding="utf-8",
    )
    print(f"wrote {OUT} entries={len(lines)}")


if __name__ == "__main__":
    main()
